import type {
  SolarWindsFormData,
  VeeamFormData,
  VmwareFormData,
  CheckpointFormData,
  CheckpointAlertRow,
  VeeamAlertRow,
  VmwareAlertRow,
} from "@/types";

export function buildSolarWindsEmailBody(fd: SolarWindsFormData): string {
  const s = fd.solarwinds;
  const lines = [
    "SolarWinds Daily Checklist",
    `Engineer: ${fd.engineer}`,
    `Date: ${fd.date}`,
    "",
    `Services Running: ${s.servicesRunning || "N/A"}`,
    ...(s.servicesRunning === "no" ? [`Service Down Ticket: ${s.serviceDownTicket || "-"}`] : []),
    `Client: ${s.client || "Multiple"}`,
    `Alerts Generated: ${s.alertsGenerated || "N/A"}`,
    "",
  ];
  if (s.alertsGenerated === "yes" && s.alerts.length > 0) {
    lines.push("Alerts:");
    s.alerts.forEach((a, i) => {
      lines.push(`#${i + 1} • ${a.alertType} | ${a.name} | ${a.details} | Time: ${a.time} | Ticket: ${a.ticket || "-"} | Notes: ${a.notes || "-"}`);
    });
  } else {
    lines.push("No alerts.");
  }
  lines.push("", "— Generated by Panoptics Infrastructure Hub —");
  return lines.join("\n");
}

export function buildVeeamEmailBody(fd: VeeamFormData): string {
  const lines = [
    "Veeam Backup Checklist",
    `Engineer: ${fd.engineer}`,
    `Date: ${fd.date}`,
    "",
    "— Clarion Events —",
    `Alerts generated: ${fd.alertsGenerated || "N/A"}`,
  ];
  if (fd.alertsGenerated === "yes" && fd.alerts.length > 0) {
    fd.alerts.forEach((a: VeeamAlertRow, i: number) => {
      lines.push(`#${i + 1} • ${a.type} | Host: ${a.vbrHost} | ${a.details} | Ticket: ${a.ticket || "-"} | Notes: ${a.notes || "-"}`);
    });
  } else {
    lines.push("No alerts.");
  }
  lines.push("", "— Local Veeam —", `Alerts generated: ${fd.localAlertsGenerated || "N/A"}`);
  if (fd.localAlertsGenerated === "yes" && fd.localAlerts.length > 0) {
    fd.localAlerts.forEach((a: VeeamAlertRow, i: number) => {
      lines.push(`#${i + 1} • ${a.type} | Host: ${a.vbrHost} | ${a.details} | Ticket: ${a.ticket || "-"} | Notes: ${a.notes || "-"}`);
    });
  } else {
    lines.push("No alerts.");
  }
  lines.push("", "— Generated by Panoptics Infrastructure Hub —");
  return lines.join("\n");
}

export function buildVmwareEmailBody(fd: VmwareFormData): string {
  const buckets = fd.vsan.alerts;
  const siteNames = { clarion: "Clarion Events", panoptics: "Panoptics Global", volac: "Volac International" } as const;

  const lines = ["VMware vSAN Checklist", `Engineer: ${fd.engineer}`, `Date: ${fd.date}`, ""];

  (Object.keys(siteNames) as (keyof typeof siteNames)[]).forEach((key) => {
    const bucket = buckets[key];
    lines.push(`— ${siteNames[key]} —`);
    lines.push(`Alerts generated: ${bucket.alert || "N/A"}`);
    if (bucket.alert === "yes" && bucket.rows.length > 0) {
      bucket.rows.forEach((r: VmwareAlertRow, i: number) => {
        lines.push(`#${i + 1} • ${r.alertType} | Host: ${r.host} | ${r.details} | Ticket: ${r.ticket || "-"} | Notes: ${r.notes || "-"}`);
      });
    } else {
      lines.push("No alerts.");
    }
    lines.push("");
  });
  lines.push("— Generated by Panoptics Infrastructure Hub —");
  return lines.join("\n");
}

export function buildCheckpointEmailBody(fd: CheckpointFormData): string {
  const sectionLines = (title: string, sec: { alertsGenerated: string; alerts: CheckpointAlertRow[] }) => {
    const arr = [`— ${title} —`, `Alerts generated: ${sec.alertsGenerated || "N/A"}`];
    if (sec.alertsGenerated === "yes" && sec.alerts.length > 0) {
      sec.alerts.forEach((a, i) => {
        arr.push(`#${i + 1} • [${a.severity}] ${a.name} | Machine: ${a.machine} | ${a.details} | Ticket: ${a.ticket || "-"}${a.notes ? " | Notes: " + a.notes : ""}`);
      });
    } else {
      arr.push("No alerts.");
    }
    return arr;
  };
  const lines = ["Checkpoint Daily Check", `Engineer: ${fd.engineer}`, `Date: ${fd.date}`, ""];
  lines.push(...sectionLines("Panoptics Global Ltd", fd.panoptics));
  lines.push("");
  lines.push(...sectionLines("The Brewery", fd.brewery));
  lines.push("", "— Generated by Panoptics Infrastructure Hub —");
  return lines.join("\n");
}

export function buildCheckpointRowBody(row: CheckpointAlertRow, title: string): string {
  return [
    `Environment: ${title}`,
    `Severity: ${row.severity || "-"}`,
    `Alert: ${row.name || "-"}`,
    `Machine: ${row.machine || "-"}`,
    `Details: ${row.details || "-"}`,
    ...(row.ticket ? [`Ticket: ${row.ticket}`] : []),
    ...(row.notes ? [`Notes: ${row.notes}`] : []),
  ].join("\n");
}

export function buildVeeamRowBody(row: VeeamAlertRow): string {
  return [
    `Type: ${row.type || "-"}`,
    `VBR Host: ${row.vbrHost || "-"}`,
    `Details: ${row.details || "-"}`,
    ...(row.ticket ? [`Ticket: ${row.ticket}`] : []),
    ...(row.notes ? [`Notes: ${row.notes}`] : []),
  ].join("\n");
}
